packages:
  # executable/launchable applications
  - apps/*
  # all packages in subdirs of packages/ and components/
  - packages/*

catalog:
  '@changesets/cli': ^2.29.7
  '@eslint/eslintrc': ^3.3.1
  '@eslint/js': ^9.39.0
  '@lingui/cli': ^5.5.2
  '@lingui/conf': ^5.5.2
  '@lingui/core': ^5.5.2
  '@lingui/detect-locale': ^5.5.2
  '@lingui/format-po': ^5.5.2
  '@lingui/macro': ^5.5.2
  '@lingui/react': ^5.5.2
  '@lingui/swc-plugin': ^5.6.1
  '@lingui/vite-plugin': ^5.5.2
  '@playwright/test': ^1.56.1
  '@radix-ui/react-accordion': ^1.2.12
  '@radix-ui/react-avatar': ^1.1.10
  '@radix-ui/react-checkbox': ^1.3.3
  '@radix-ui/react-collapsible': ^1.1.12
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-progress': ^1.1.7
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-slider': ^1.3.6
  '@radix-ui/react-slot': ^1.2.3
  '@radix-ui/react-switch': ^1.2.6
  '@radix-ui/react-tabs': ^1.1.13
  '@radix-ui/react-toast': ^1.2.15
  '@radix-ui/react-toggle': ^1.1.10
  '@radix-ui/react-tooltip': ^1.2.8
  '@rainbow-me/rainbowkit': 2.2.9
  '@tailwindcss/vite': ^4.1.16
  '@tanstack/eslint-plugin-query': ^5.91.2
  '@tanstack/react-query': ^5.90.5
  '@testing-library/dom': ^10.4.1
  '@testing-library/react': ^16.3.0
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@typescript-eslint/eslint-plugin': ^8.46.2
  '@typescript-eslint/parser': ^8.46.2
  '@vitejs/plugin-react-swc': ^3.11.0
  '@vitest/coverage-v8': ^3.2.4
  '@wagmi/cli': ^2.5.1
  '@wagmi/core': ^2.22.1
  class-variance-authority: ^0.7.1
  clsx: ^2.1.0
  date-fns: ^3.6.0
  dotenv: ^16.6.1
  embla-carousel-autoplay: ^8.6.0
  embla-carousel-fade: ^8.6.0
  embla-carousel-react: ^8.6.0
  eslint: ^9.39.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-testing-library: ^7.13.3
  ethers: ^6.15.0
  framer-motion: ^11.18.2
  globals: ^15.15.0
  graphql: ^16.11.0
  graphql-request: ^7.3.1
  happy-dom: ^20.0.10
  husky: ^9.0.11
  knip: ^5.66.4
  lint-staged: ^15.5.1
  lucide-react: ^0.544.0
  openapi-fetch: ^0.15.0
  prettier: ^3.6.1
  prettier-plugin-tailwindcss: ^0.7.1
  react: ^19.2.3
  react-dom: ^19.2.3
  react-intersection-observer: ^9.16.0
  react-jazzicon: ^1.0.4
  react-markdown: ^9.1.0
  react-router-dom: ^6.30.1
  recharts: ^2.15.4
  rehype-sanitize: ^6.0.0
  rollup-plugin-visualizer: ^5.14.0
  sonner: ^2.0.7
  tailwind-merge: ^2.6.0
  tailwindcss: ^4.1.16
  tailwindcss-animate: ^1.0.7
  tiny-invariant: ^1.3.1
  typescript: 5.9.3
  viem: ^2.38.6
  vite: ^7.1.12
  vite-plugin-dts: ^4.5.4
  vite-plugin-node-polyfills: ^0.24.0
  vite-plugin-simple-html: ^1.0.1
  vite-plugin-static-copy: ^3.1.4
  vitest: ^3.2.4
  vitest-canvas-mock: ^0.3.3
  wagmi: ^2.19.2
  zod: ^3.25.76

catalogMode: strict

cleanupUnusedCatalogs: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - happy-dom
