packages:
  - apps/*
  - packages/*

catalog:
  '@base-org/account': ~2.4.0
  '@binance/w3w-wagmi-connector-v2': ^1.2.11
  '@changesets/cli': ^2.29.8
  '@coinbase/wallet-sdk': ~4.3.6
  '@eslint/eslintrc': ^3.3.3
  '@eslint/js': ^9.39.2
  '@lingui/cli': ^5.7.0
  '@lingui/conf': ^5.7.0
  '@lingui/core': ^5.7.0
  '@lingui/detect-locale': ^5.7.0
  '@lingui/format-po': ^5.7.0
  '@lingui/macro': ^5.7.0
  '@lingui/react': ^5.7.0
  '@lingui/swc-plugin': ^5.7.0
  '@lingui/vite-plugin': ^5.7.0
  '@metamask/sdk': ~0.33.1
  '@playwright/test': ^1.57.0
  '@radix-ui/react-accordion': ^1.2.12
  '@radix-ui/react-avatar': ^1.1.11
  '@radix-ui/react-checkbox': ^1.3.3
  '@radix-ui/react-collapsible': ^1.1.12
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-progress': ^1.1.8
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-slider': ^1.3.6
  '@radix-ui/react-slot': ^1.2.4
  '@radix-ui/react-switch': ^1.2.6
  '@radix-ui/react-tabs': ^1.1.13
  '@radix-ui/react-toast': ^1.2.15
  '@radix-ui/react-toggle': ^1.1.10
  '@radix-ui/react-tooltip': ^1.2.8
  '@safe-global/safe-apps-provider': ~0.18.6
  '@safe-global/safe-apps-sdk': ~9.1.0
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/eslint-plugin-query': ^5.91.2
  '@tanstack/react-query': ^5.90.16
  '@testing-library/dom': ^10.4.1
  '@testing-library/react': ^16.3.1
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@typescript-eslint/eslint-plugin': ^8.52.0
  '@typescript-eslint/parser': ^8.52.0
  '@vitejs/plugin-react-swc': ^4.2.2
  '@vitest/coverage-v8': ^3.2.4
  '@wagmi/cli': ^2.8.0
  '@wagmi/core': ^3.0.2
  '@walletconnect/ethereum-provider': ~2.21.1
  class-variance-authority: ^0.7.1
  clsx: ^2.1.0
  date-fns: ^3.6.0
  dotenv: ^16.6.1
  embla-carousel-autoplay: ^8.6.0
  embla-carousel-fade: ^8.6.0
  embla-carousel-react: ^8.6.0
  eslint: ^9.39.2
  eslint-plugin-react: ^7.37.5
  eslint-plugin-testing-library: ^7.15.4
  ethers: ^6.16.0
  framer-motion: ^11.18.2
  globals: ^15.15.0
  graphql: ^16.12.0
  graphql-request: ^7.4.0
  happy-dom: ^20.0.11
  husky: ^9.0.11
  knip: ^5.80.0
  lint-staged: ^15.5.1
  lucide-react: ^0.563.0
  openapi-fetch: ^0.15.0
  porto: ~0.2.37
  prettier: ^3.6.1
  prettier-plugin-tailwindcss: ^0.7.2
  react: ^19.2.3
  react-dom: ^19.2.3
  react-intersection-observer: ^9.16.0
  react-jazzicon: ^1.0.4
  react-markdown: ^9.1.0
  react-router-dom: ^6.30.2
  recharts: ^2.15.4
  rehype-sanitize: ^6.0.0
  rollup-plugin-visualizer: ^5.14.0
  sonner: ^2.0.7
  tailwind-merge: ^2.6.1
  tailwindcss: ^4.1.17
  tailwindcss-animate: ^1.0.7
  tiny-invariant: ^1.3.1
  typescript: 5.9.3
  viem: ^2.43.4
  vite: ^7.3.0
  vite-plugin-dts: ^4.5.4
  vite-plugin-node-polyfills: ^0.24.0
  vite-plugin-simple-html: ^1.1.0
  vite-plugin-static-copy: ^3.1.4
  vitest: ^3.2.4
  vitest-canvas-mock: ^0.3.3
  wagmi: ^3.1.4
  zod: ^4.1.11

catalogMode: strict

cleanupUnusedCatalogs: true

minimumReleaseAge: 1440

trustPolicy: no-downgrade
