export enum Intent {
  TRADE_INTENT = 'TRADE_INTENT',
  UPGRADE_INTENT = 'UPGRADE_INTENT',
  REWARDS_INTENT = 'REWARDS_INTENT',
  SAVINGS_INTENT = 'SAVINGS_INTENT',
  BALANCES_INTENT = 'BALANCES_INTENT',
  SEAL_INTENT = 'SEAL_INTENT',
  STAKE_INTENT = 'STAKE_INTENT',
  EXPERT_INTENT = 'EXPERT_INTENT',
  VAULTS_INTENT = 'VAULTS_INTENT',
  CONVERT_INTENT = 'CONVERT_INTENT'
}

export enum ExpertIntent {
  STUSDS_INTENT = 'STUSDS_INTENT'
}

export enum VaultsIntent {
  MORPHO_VAULT_INTENT = 'MORPHO_VAULT_INTENT'
}

export enum ConvertIntent {
  UPGRADE_INTENT = 'UPGRADE_INTENT',
  TRADE_INTENT = 'TRADE_INTENT'
}
