export enum Intent {
  TRADE_INTENT = 'TRADE_INTENT',
  UPGRADE_INTENT = 'UPGRADE_INTENT',
  REWARDS_INTENT = 'REWARDS_INTENT',
  SAVINGS_INTENT = 'SAVINGS_INTENT',
  STUSDS_INTENT = 'STUSDS_INTENT',
  BALANCES_INTENT = 'BALANCES_INTENT',
  SEAL_INTENT = 'SEAL_INTENT',
  STAKE_INTENT = 'STAKE_INTENT',
  ADVANCED_INTENT = 'ADVANCED_INTENT'
}
